[package]
name = "s1g-tools"
description = "CLI tools: s1g-tx, s1g-rx, s1g-sim"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
s1g-phy.workspace = true
s1g-dsp.workspace = true
s1g-sdr.workspace = true
num-complex.workspace = true
anyhow.workspace = true
clap.workspace = true
rand.workspace = true

[dependencies.s1g-sdr-pluto]
workspace = true
optional = true

[features]
default = ["pluto"]
pluto = ["dep:s1g-sdr-pluto"]

[[bin]]
name = "s1g-tx"
path = "src/bin/s1g-tx.rs"

[[bin]]
name = "s1g-rx"
path = "src/bin/s1g-rx.rs"

[[bin]]
name = "s1g-sim"
path = "src/bin/s1g-sim.rs"
